/**
 * Peter Parker Config Generator
 *
 * Generates .ralph-tui/config.toml with model-routed multi-agent setup.
 * Peter Parker wraps ralph-tui as the orchestrator.
 *
 * @purpose Generate ralph-tui TOML config with model routing per agent role
 */

import * as fs from "fs"
import * as path from "path"
import type { AgentRole, CostProfile, ModelTier } from "../types/map.js"
import { MODEL_ROUTING_TABLE, FALLBACK_ROUTING } from "../types/map.js"

const ROLES: AgentRole[] = ["scout", "planner", "builder", "reviewer", "tester"]

interface AgentConfig {
  name: string
  model: ModelTier
  isDefault: boolean
  skipPermissions: boolean
}

function buildAgents(profile: CostProfile): AgentConfig[] {
  const routing = MODEL_ROUTING_TABLE[profile]
  const agents: AgentConfig[] = []

  for (const role of ROLES) {
    agents.push({
      name: role,
      model: routing[role],
      isDefault: role === "builder",
      skipPermissions: true,
    })

    agents.push({
      name: `${role}-fallback`,
      model: FALLBACK_ROUTING[role],
      isDefault: false,
      skipPermissions: true,
    })
  }

  return agents
}

function toToml(agents: AgentConfig[]): string {
  const lines: string[] = [
    `# Generated by Peter Parker - regenerate with: jfl peter setup`,
    `configVersion = "1"`,
    `maxIterations = 0`,
    `autoCommit = true`,
    ``,
  ]

  for (const agent of agents) {
    lines.push(`[[agents]]`)
    lines.push(`name = "${agent.name}"`)
    lines.push(`plugin = "claude"`)
    if (agent.isDefault) {
      lines.push(`default = true`)
    }
    lines.push(`[agents.options]`)
    lines.push(`model = "${agent.model}"`)
    lines.push(`skipPermissions = ${agent.skipPermissions}`)
    lines.push(``)
  }

  return lines.join("\n")
}

export function generatePeterParkerConfig(profile: CostProfile): string {
  const agents = buildAgents(profile)
  return toToml(agents)
}

export function writePeterParkerConfig(
  projectRoot: string,
  profile: CostProfile
): string {
  const configDir = path.join(projectRoot, ".ralph-tui")
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true })
  }

  const configPath = path.join(configDir, "config.toml")
  const content = generatePeterParkerConfig(profile)
  fs.writeFileSync(configPath, content)

  return configPath
}

export function readCurrentProfile(projectRoot: string): CostProfile | null {
  const configPath = path.join(projectRoot, ".ralph-tui", "config.toml")
  if (!fs.existsSync(configPath)) return null

  const content = fs.readFileSync(configPath, "utf-8")
  if (!content.includes("Generated by Peter Parker")) return null

  // Infer profile from scout model
  const scoutMatch = content.match(/\[\[agents\]\]\nname = "scout"\nplugin = "claude"\n\[agents\.options\]\nmodel = "(\w+)"/)
  if (!scoutMatch) return null

  const scoutModel = scoutMatch[1] as ModelTier
  if (scoutModel === "haiku") return "balanced"
  if (scoutModel === "sonnet") return "quality-first"
  return "cost-optimized"
}
