/**
 * @purpose Self-improvement loop: analyze telemetry, generate suggestions, optionally create GitHub issues
 */

import chalk from 'chalk'
import { execSync } from 'child_process'
import { telemetry } from '../lib/telemetry.js'
import { loadLocalEvents, analyzeEvents, generateSuggestions, formatDigest } from '../lib/telemetry-digest.js'
import type { ImprovementSuggestion } from '../types/telemetry-digest.js'

interface ImproveOptions {
  dryRun?: boolean
  auto?: boolean
  hours?: string
}

export async function improveCommand(options: ImproveOptions): Promise<void> {
  const hours = parseInt(options.hours || '24', 10) || 24

  const events = [
    ...loadLocalEvents(),
    ...telemetry.getSpilloverEvents(),
  ]

  const uniqueEvents = Array.from(
    new Map(events.map(e => [e.event_id, e])).values()
  )

  if (uniqueEvents.length === 0) {
    console.log(chalk.gray('\n  No telemetry events found. Run some commands first.\n'))
    return
  }

  const digest = analyzeEvents(uniqueEvents, hours)
  const suggestions = generateSuggestions(digest)

  console.log(formatDigest(digest, 'text'))

  if (suggestions.length === 0) {
    console.log(chalk.green('\n  No improvement suggestions — everything looks healthy.\n'))
    return
  }

  const actionable = suggestions.filter(s => s.severity === 'high' || s.severity === 'medium')

  console.log(chalk.bold(`\n  ${suggestions.length} Improvement Suggestions`))
  console.log(chalk.gray(`  (${actionable.length} actionable)\n`))

  for (const s of suggestions) {
    const severityLabel = s.severity === 'high' ? chalk.red(`[${s.severity}]`) :
      s.severity === 'medium' ? chalk.yellow(`[${s.severity}]`) :
      chalk.gray(`[${s.severity}]`)
    const typeLabel = chalk.cyan(`[${s.type}]`)
    console.log(`  ${severityLabel} ${typeLabel} ${s.title}`)
    console.log(chalk.gray(`    ${s.description}`))
    console.log(chalk.white(`    Fix: ${s.suggestedFix}`))
    console.log()
  }

  const hookSuggestions = suggestions.filter(s => s.type === 'usage')
  if (hookSuggestions.length > 0) {
    console.log(chalk.bold(`\n  Hook Insights`))
    for (const s of hookSuggestions) {
      console.log(chalk.cyan(`    ${s.title}`))
      console.log(chalk.gray(`    ${s.description}\n`))
    }
  }

  if (options.dryRun) {
    console.log(chalk.gray(`  --dry-run: Would create ${actionable.length} GitHub issues.\n`))
    return
  }

  if (options.auto && actionable.length > 0) {
    console.log(chalk.bold(`  Creating ${actionable.length} GitHub issues...\n`))

    for (const s of actionable) {
      try {
        const title = `[jfl-improve] ${s.title}`
        const body = [
          `**Type:** ${s.type}`,
          `**Severity:** ${s.severity}`,
          '',
          s.description,
          '',
          `**Suggested Fix:** ${s.suggestedFix}`,
          '',
          `_Auto-generated by \`jfl improve\` at ${new Date().toISOString()}_`,
        ].join('\n')

        const result = execSync(
          `gh issue create --title "${title.replace(/"/g, '\\"')}" --body "${body.replace(/"/g, '\\"')}" --label "jfl-improve" 2>&1`,
          { encoding: 'utf-8', timeout: 15000 }
        ).trim()

        console.log(chalk.green(`  Created: ${result}`))
      } catch (err: any) {
        const msg = err.stderr || err.message || 'Unknown error'
        console.log(chalk.red(`  Failed to create issue for "${s.title}": ${msg}`))
      }
    }
    console.log()
  }
}
