#!/bin/bash
# scripts/pp-branch-pr.sh
#
# Wraps Peter Parker agent execution in git branch + PR workflow.
# Creates a branch, runs the agent, commits changes, opens a PR,
# and posts a pr:created event to the hub.
#
# Called by flow engine spawn action or directly.
#
# Usage: pp-branch-pr.sh <task-description> [hub-url] [hub-token]

set -euo pipefail

TASK="${1:?Usage: pp-branch-pr.sh <task-description> [hub-url] [hub-token]}"
HUB_URL="${2:-}"
HUB_TOKEN="${3:-}"
BRANCH_NAME="pp/fix-$(date +%s)"
BASE_BRANCH="main"

if [ -z "$HUB_URL" ] && [ -f ".jfl/context-hub.port" ]; then
  PORT=$(cat .jfl/context-hub.port)
  HUB_URL="http://localhost:${PORT}"
fi
if [ -z "$HUB_TOKEN" ] && [ -f ".jfl/context-hub.token" ]; then
  HUB_TOKEN=$(cat .jfl/context-hub.token)
fi

echo "PP: Creating branch ${BRANCH_NAME}"

# 1. Create branch from clean main
git fetch origin "${BASE_BRANCH}" 2>/dev/null || true
git checkout -b "${BRANCH_NAME}" "origin/${BASE_BRANCH}" 2>/dev/null || git checkout -b "${BRANCH_NAME}" "${BASE_BRANCH}"

# 2. Run Peter Parker
echo "PP: Running agent on task: ${TASK}"
jfl peter run --task "${TASK}"

# 3. Check if anything changed
if git diff --quiet HEAD && [ -z "$(git ls-files --others --exclude-standard)" ]; then
  echo "PP: No changes made, cleaning up"
  git checkout "${BASE_BRANCH}" 2>/dev/null || true
  git branch -D "${BRANCH_NAME}" 2>/dev/null || true
  exit 0
fi

# 4. Commit
git add -A
COMMIT_MSG="fix(pp): ${TASK}

Agent: peter-parker
Branch: ${BRANCH_NAME}
Auto-generated by JFL self-driving loop

Co-authored-by: Peter Parker <pp@jfl.dev>"

git commit -m "${COMMIT_MSG}"

# 5. Push
git push -u origin "${BRANCH_NAME}"

# 6. Create PR
PR_TITLE="PP: $(echo "${TASK}" | head -c 60)"
PR_BODY="## Auto-generated by Peter Parker

**Task:** ${TASK}
**Branch:** \`${BRANCH_NAME}\`

### Eval Suite
This PR will be evaluated by the CI eval suite.
Auto-merge will trigger if eval score improves over baseline.

---
*Generated by JFL self-driving loop*"

PR_URL=$(gh pr create \
  --title "${PR_TITLE}" \
  --body "${PR_BODY}" \
  --base "${BASE_BRANCH}" \
  --head "${BRANCH_NAME}" \
  --label "pp-generated" 2>&1) || {
  echo "PP: Label may not exist, retrying without label"
  PR_URL=$(gh pr create \
    --title "${PR_TITLE}" \
    --body "${PR_BODY}" \
    --base "${BASE_BRANCH}" \
    --head "${BRANCH_NAME}" 2>&1)
}

echo "PP: PR created at ${PR_URL}"

# 7. Post event to hub
if [ -n "${HUB_URL}" ]; then
  TASK_JSON=$(printf '%s' "${TASK}" | python3 -c 'import sys,json; print(json.dumps(sys.stdin.read().strip()))')

  CURL_ARGS=(-s -X POST "${HUB_URL}/api/events" -H "Content-Type: application/json")
  if [ -n "${HUB_TOKEN}" ]; then
    CURL_ARGS+=(-H "Authorization: Bearer ${HUB_TOKEN}")
  fi
  CURL_ARGS+=(-d "{
    \"type\": \"pr:created\",
    \"source\": \"peter-parker\",
    \"data\": {
      \"task\": ${TASK_JSON},
      \"pr_url\": \"${PR_URL}\",
      \"branch\": \"${BRANCH_NAME}\"
    }
  }")

  curl "${CURL_ARGS[@]}" 2>/dev/null || echo "PP: Warning - could not post event to hub"
fi

# 8. Return to base branch
git checkout "${BASE_BRANCH}" 2>/dev/null || true

echo "PP: Done"
