/**
 * Tests for Peter Parker Config Generator
 *
 * @purpose Test TOML config generation for model routing
 */

import { generatePeterParkerConfig } from '../peter-parker-config'
import type { CostProfile } from '../../types/map'

describe('generatePeterParkerConfig', () => {
  const profiles: CostProfile[] = ['cost-optimized', 'balanced', 'quality-first']

  describe('generates valid TOML for all profiles', () => {
    it.each(profiles)('generates valid config for %s profile', (profile) => {
      const toml = generatePeterParkerConfig(profile)

      // Should be a non-empty string
      expect(typeof toml).toBe('string')
      expect(toml.length).toBeGreaterThan(0)

      // Should contain standard TOML header
      expect(toml).toContain('configVersion = "1"')
      expect(toml).toContain('autoCommit = true')
    })
  })

  describe('contains required agents', () => {
    it.each(profiles)('includes all 5 agent roles for %s profile', (profile) => {
      const toml = generatePeterParkerConfig(profile)
      const roles = ['scout', 'planner', 'builder', 'reviewer', 'tester']

      for (const role of roles) {
        expect(toml).toContain(`name = "${role}"`)
        expect(toml).toContain(`name = "${role}-fallback"`)
      }
    })

    it('marks builder as default agent', () => {
      const toml = generatePeterParkerConfig('balanced')

      // builder section should have default = true
      const builderSection = toml.split('[[agents]]').find(s => s.includes('name = "builder"') && !s.includes('fallback'))
      expect(builderSection).toContain('default = true')
    })
  })

  describe('uses correct models per profile', () => {
    it('cost-optimized uses haiku for scout', () => {
      const toml = generatePeterParkerConfig('cost-optimized')

      // Find scout section (not scout-fallback)
      const sections = toml.split('[[agents]]')
      const scoutSection = sections.find(s => s.includes('name = "scout"') && !s.includes('fallback'))

      expect(scoutSection).toContain('model = "haiku"')
    })

    it('quality-first uses sonnet for scout', () => {
      const toml = generatePeterParkerConfig('quality-first')

      const sections = toml.split('[[agents]]')
      const scoutSection = sections.find(s => s.includes('name = "scout"') && !s.includes('fallback'))

      expect(scoutSection).toContain('model = "sonnet"')
    })

    it('quality-first uses opus for planner', () => {
      const toml = generatePeterParkerConfig('quality-first')

      const sections = toml.split('[[agents]]')
      const plannerSection = sections.find(s => s.includes('name = "planner"') && !s.includes('fallback'))

      expect(plannerSection).toContain('model = "opus"')
    })

    it('balanced uses opus for reviewer', () => {
      const toml = generatePeterParkerConfig('balanced')

      const sections = toml.split('[[agents]]')
      const reviewerSection = sections.find(s => s.includes('name = "reviewer"') && !s.includes('fallback'))

      expect(reviewerSection).toContain('model = "opus"')
    })
  })

  describe('fallback agents', () => {
    it.each(profiles)('includes fallback agents for all roles in %s', (profile) => {
      const toml = generatePeterParkerConfig(profile)

      // All roles should have fallback variants
      const fallbackRoles = ['scout-fallback', 'planner-fallback', 'builder-fallback', 'reviewer-fallback', 'tester-fallback']

      for (const role of fallbackRoles) {
        expect(toml).toContain(`name = "${role}"`)
      }
    })

    it('fallback agents use appropriate models', () => {
      const toml = generatePeterParkerConfig('balanced')

      const sections = toml.split('[[agents]]')

      // Builder fallback should use opus
      const builderFallback = sections.find(s => s.includes('name = "builder-fallback"'))
      expect(builderFallback).toContain('model = "opus"')

      // Scout fallback should use sonnet
      const scoutFallback = sections.find(s => s.includes('name = "scout-fallback"'))
      expect(scoutFallback).toContain('model = "sonnet"')
    })
  })

  describe('TOML structure', () => {
    it('includes comment about regeneration', () => {
      const toml = generatePeterParkerConfig('balanced')

      expect(toml).toContain('Generated by Peter Parker')
      expect(toml).toContain('jfl peter setup')
    })

    it('all agents use claude plugin', () => {
      const toml = generatePeterParkerConfig('balanced')

      // Every [[agents]] section should have plugin = "claude"
      const agentSections = toml.split('[[agents]]').filter(s => s.trim().length > 0)

      for (const section of agentSections) {
        if (section.includes('name = ')) {
          expect(section).toContain('plugin = "claude"')
        }
      }
    })

    it('all agents have skipPermissions = true', () => {
      const toml = generatePeterParkerConfig('balanced')

      const agentSections = toml.split('[[agents]]').filter(s => s.includes('name = '))

      for (const section of agentSections) {
        expect(section).toContain('skipPermissions = true')
      }
    })

    it('uses [agents.options] for model config', () => {
      const toml = generatePeterParkerConfig('balanced')

      // Each agent should have an options section
      expect(toml).toContain('[agents.options]')

      // Count should match number of agents (5 roles * 2 = 10 agents)
      const optionsCount = (toml.match(/\[agents\.options\]/g) || []).length
      expect(optionsCount).toBe(10)
    })
  })
})
